version: '3.8'

services:
  db:
    image: postgres:17
    container_name: investment_db
    environment:
      POSTGRES_DB: investments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: investment_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: investments
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  db_data:
